CREATE TABLE tblParabirim
(
Birim_id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Birim CHAR(50)  NOT NULL
)
GO

CREATE TABLE tblHesapTuru
(
Tur_id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Tur CHAR(50) NOT NULL
)
GO

CREATE TABLE tblSube
(
Isim CHAR(50) PRIMARY KEY NOT NULL,
Sehir CHAR(50) NOT NULL
)
GO

CREATE TABLE tblHesap
(
Hesap_no CHAR(7) PRIMARY KEY  NOT NULL,
Olusturma_tarihi DATE NOT NULL,
Kapatilma_tarihi DATE ,
Durum SMALLINT DEFAULT 1 NOT NULL,
Tutar INT NOT NULL,
Tur_id1 INT FOREIGN KEY REFERENCES tblHesapTuru(Tur_id),
Tur_id2 INT FOREIGN KEY REFERENCES tblHesapTuru(Tur_id),
Para_birimi INT FOREIGN KEY REFERENCES tblParabirim(Birim_id) NOT NULL,
Sube_isim CHAR(50) FOREIGN KEY REFERENCES tblSube(Isim)
)
GO

CREATE TABLE tblEft
(
Eft_tur CHAR(50) PRIMARY KEY NOT NULL,
gidenHesap_no CHAR(7) NOT NULL,
Tarih DATE DEFAULT GETDATE() NOT NULL,
Tutar INT NOT NULL,
Hesap_no CHAR(7) FOREIGN KEY REFERENCES tblHesap(Hesap_no)
)
GO

CREATE TABLE tblKrediKarti
(
KartNo CHAR(7) PRIMARY KEY NOT NULL,
OlusturulmaTarih DATE NOT NULL,
Limit INT ,
Hesap_no CHAR(7) FOREIGN KEY REFERENCES tblHesap(Hesap_no) NOT NULL
)
GO

CREATE TABLE tblKrediKartiHarcama
(
H_id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
KartNo CHAR(7) FOREIGN KEY REFERENCES tblKrediKarti(KartNo) NOT NULL,
Htarih DATE NOT NULL,
Htur CHAR(50)  NOT NULL,
HTutar INT NOT NULL,
SonTarih DATE NOT NULL
)
GO

CREATE TABLE tblCalisanTipi
(
C_Tip CHAR(50) PRIMARY KEY NOT NULL
)
GO

CREATE TABLE tblCalisan
(
Calisan_id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Isim CHAR(50) NOT NULL,
baslamaTarihi DATE NOT NULL,
Adres VARCHAR(50) NOT NULL,
TelNo CHAR(11) NOT NULL,
Maas INT NOT NULL,
SubeIsim CHAR(50) FOREIGN KEY REFERENCES tblSube(Isim) NOT NULL,
C_Tip CHAR(50) FOREIGN KEY REFERENCES tblCalisanTipi(C_Tip) NOT NULL
)
GO

CREATE TABLE tblOdeme
(
O_id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
O_tür CHAR(50) NOT NULL,
OTarih DATE NOT NULL,
OTutar INT NOT NULL,
OdemeCalisan_id INT FOREIGN KEY REFERENCES tblCalisan(Calisan_id) NOT NULL
)
GO

CREATE TABLE tblMusteri
(
M_id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
M_isim CHAR(50) NOT NULL,
Adres VARCHAR(200) NOT NULL,
TelNo CHAR(11) NOT NULL,
Hesap_no CHAR(7) FOREIGN KEY REFERENCES tblHesap(Hesap_no) NOT NULL
)
GO

CREATE TABLE tblBankaKarti
(
Kart_no CHAR(9) PRIMARY KEY NOT NULL,
CVC CHAR(3) NOT NULL,
Durum SMALLINT DEFAULT 1 NOT NULL,
OlusturulmaTarihi DATE NOT NULL,
Hesap_no CHAR(7) FOREIGN KEY REFERENCES tblHesap(Hesap_no)
)
GO

CREATE TABLE tblIslemTurleri
(
Islem_tur CHAR(50) PRIMARY KEY  NOT NULL
)
GO

CREATE TABLE tblFirma
(
Firma_isim CHAR(50) PRIMARY KEY NOT NULL
)
GO

CREATE TABLE tblBankaKartiIslemleri
(
Islem_id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Tutar INT NOT NULL,
Tarih DATE NOT NULL,
Kart_no CHAR(9) FOREIGN KEY REFERENCES tblBankaKarti(Kart_no) NOT NULL,
Islem_tur CHAR(50) FOREIGN KEY REFERENCES tblIslemTurleri(Islem_tur) NOT NULL,
Firma_Isim CHAR(50) FOREIGN KEY REFERENCES tblFirma(Firma_isim) NOT NULL
)
GO

CREATE TABLE tblKrediKartýIslemleri
(
Islem_id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Tutar INT NOT NULL,
Tarih DATE NOT NULL,
Kart_no CHAR(7) FOREIGN KEY REFERENCES tblKrediKarti(KartNo) NOT NULL,
Islem_tur CHAR(50) FOREIGN KEY REFERENCES tblIslemTurleri(Islem_tur) NOT NULL,
Firma_Isim CHAR(50) FOREIGN KEY REFERENCES tblFirma(Firma_isim) NOT NULL
)
GO
